Task 01

In [11]:
numbers = ("3", "45", "83", "21")

with open("numbers.txt", "w") as myfile:
    myfile.close()

with open("numbers.txt", "a+") as myfile:
    myfile.seek(0)

    for i in range(len(numbers)):
        myfile.write(numbers[i])
        myfile.write("\n")



Task 02

In [12]:
def converter(per):
    if 100 >= per > 70 :
        return "Good"
    elif 70>= per > 50 :
        return "Average"
    else :
        return "Fail"

percentage = int(input("Enter your percentage mark: "))  

print(converter(percentage))

Good


Numpy Task 01

In [13]:
import numpy as np
array = np.arange(0,10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


Numpy Task 02

In [17]:
import numpy as np
array = np.random.rand(3,3)
print(array)

b_array = array <1
print(b_array)

[[0.72554848 0.83692565 0.00395104]
 [0.81582811 0.26513012 0.49115994]
 [0.94837217 0.92211833 0.58126902]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Numpy Task 03

In [59]:
import numpy as np
array = np.arange(1,11)
print(array[0:10:2])

[1 3 5 7 9]


Numpy Task 04

In [ ]:
import numpy as np
array = np.arange(1,11)

for i in range(0, len(array),2):
    array[i] = -1

print(array)

Numpy Task 05

In [62]:
import numpy as np
array = np.arange(0,4)
n_array = array.reshape(2,2)
print(n_array)

[[0 1]
 [2 3]]


Numpy Task 06

In [66]:
import numpy as np

array_01 = np.random.rand(3,3)
array_02 = np.random.rand(3,3)

c= np.dot(array_01, array_02)
d = np.sum(c)

print(c)
print(d)

[[1.05203508 1.54357229 0.91239454]
 [1.01664743 1.60934987 0.7569222 ]
 [0.8598941  1.16080452 0.82965758]]
9.741277623181208
